version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:0.7.4-pg16
    container_name: pgvector-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    # restart: always
