services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:2.2.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8080:80"
    volumes:
      - ${HF_HOME}/hub:/data
    command: >
      --model-id AMead10/Llama-3.2-1B-Instruct-AWQ
      --max-input-length 4000
      --max-total-tokens 4096
