services:
    directus:
        image: directus/directus:12.0.2
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "replace-with-random-value"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"
            PUBLIC_URL: "http://localhost:8055/"
            LICENSE_KEY: ""
