version: '3.8'

services:
  echo-bot:
    build: .
    container_name: echo-bot
    ports:
      - "3978:3978"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    command: ["python", "app.py"]

